language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - nosetests  --with-coverage  # or py.test for Python versions 3.5 and below
after_success:
  - coveralls
