language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls
services:
  - postgresql
before_script:
  - psql -c 'create database weconnect_test;' -U postgres
  - flask db upgrade
# command to run tests
script:
  - nosetests --with-coverage --cover-package=app  # or py.test for Python versions 3.5 and below
after_success:
  - coveralls
