"""empty message

Revision ID: 56a38a84cd6c
Revises: d7496692b83d
Create Date: 2018-07-30 21:49:36.145351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a38a84cd6c'
down_revision = 'd7496692b83d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('logo', sa.String(length=128), nullable=True))
    op.drop_column('businesses', 'logos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('logos', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('businesses', 'logo')
    # ### end Alembic commands ###
