"""empty message

Revision ID: 92b065154d5d
Revises: 9b48ba0f73d3
Create Date: 2018-07-30 21:45:11.831667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b065154d5d'
down_revision = '9b48ba0f73d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('logo', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'logo')
    # ### end Alembic commands ###
