"""empty message

Revision ID: 9b48ba0f73d3
Revises: d7507d4d79be
Create Date: 2018-06-14 16:11:16.012521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b48ba0f73d3'
down_revision = 'd7507d4d79be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_column('businesses', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('bio', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('businesses', 'description')
    # ### end Alembic commands ###
