"""empty message

Revision ID: d7496692b83d
Revises: 92b065154d5d
Create Date: 2018-07-30 21:49:13.047537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7496692b83d'
down_revision = '92b065154d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('logos', sa.String(length=128), nullable=True))
    op.drop_column('businesses', 'logo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('logo', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('businesses', 'logos')
    # ### end Alembic commands ###
